name: "Replace source version"
description: "Common steps to replace `unknown-version` and `0.0.0` string in the source code"
runs:
  using: composite
  steps:
    - name: Update source version
      shell: bash
      run: |
        [[ "${GITHUB_REF_NAME}" =~ ^version-.*$ ]] && VERSION=${GITHUB_REF_NAME:8} || VERSION=0.0.0;
        echo "VERSION = ${VERSION}";
        for placeholder in "unknown-version 0\.0\.0"; do
            find . "(" -name "*.py" -o -name "*.toml" -o -name "*.js" -o - name "*.json" ")" -a -type f | 
                xargs sed -i "s/${placeholder}/${VERSION}/g" 
        done
