name: "Replace source version"
description: "Common steps to replace `unknown-version` and `0.0.0` string in the source code"
inputs:
  max-depth:
    description: "How deep to look into source tree"
    required: false
    default: 3
  files:
    description: "A list of space-separated explicit files to be considered when replacing versions"
    required: false
    default: ""
  exclude-patterns:
    description: "A list of space-separated filename patterns to exclude from replacement"
    required: false
    default: "package-lock.json"
runs:
  using: composite
  steps:
    - name: Extract version from tag
      uses: qtoggle/actions-common/actions/extract-version-from-tag@v1
    - name: Update source version
      shell: bash
      run: |
        exclude_args=""
        for pattern in ${{ inputs.exclude-patterns }}; do
            exclude_args="${exclude_args} -not -name ${pattern}"
        done
        for placeholder in unknown-version "0\.0\.0"; do
            find . -maxdepth ${{ inputs.max-depth }} \
                "(" -name "*.py" -o -name "*.toml" -o -name "*.js" -o -name "*.json" ")" -a -type f \
                ${exclude_args} | \
                xargs sed -i "s/${placeholder}/${{ env.VERSION }}/g"
            for file in ${{ inputs.files }}; do
                sed -i "s/${placeholder}/${{ env.VERSION }}/g" ${file}
            done
        done
