name: "Replace source version"
description: "Common steps to replace `unknown-version` and `0.0.0` string in the source code"
inputs:
  max-depth:
    description: "How deep to look into source tree"
    required: false
    default: 3
runs:
  using: composite
  steps:
    - name: Extract version from tag
      uses: qtoggle/actions-common/actions/extract-version-from-tag@v1
    - name: Update source version
      shell: bash
      run: |
        for placeholder in unknown-version "0\.0\.0"; do
            find . "(" -name "*.py" -o -name "*.toml" -o -name "*.js" -o -name "*.json" ")" -a -type f \
                 -maxdepth ${{ inputs.max-depth }} |
                 xargs sed -i "s/${placeholder}/${{ env.VERSION }}/g" 
        done
