name: "Lint JavaScript"
description: "Common steps to lint JS code using `ESLint`"
inputs:
  work-dir:
    description: "Will change to this directory"
    required: false
    default: .
  source-dir:
    description: "Source directory to lint"
    required: false
    default: js
runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Replace source version
      uses: qtoggle/actions-common/actions/replace-source-version@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dev deps
      shell: bash
      run: cd ${{ inputs.work-dir }} && npm i --include=dev
    - name: ESLint
      shell: bash
      run: cd ${{ inputs.work-dir }} && npx eslint ${{ inputs.source-dir }}
