name: "Build Python package"
description: "Common steps to build Python package"
runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Replace source version
      uses: qtoggle/actions-common/actions/replace-source-version@v1
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install UV
      uses: astral-sh/setup-uv@v6
    - name: Build Python package
      shell: bash
      run: uv build
    - name: Store dist folder
      uses: actions/upload-artifact@v4
      with:
        name: python-package-dist
        path: dist/
