name: "Build Python package"
description: "Common steps to build Python package"
inputs:
  private:
    description: "Whether to publish to public PyPI index or a private one"
    default: no

runs:
  using: composite
  steps:
    - name: Fetch dist folder
      uses: actions/download-artifact@v4
      with:
        name: python-package-dist
        path: dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ inputs.private == 'yes' && secrets.PRIVATE_PYPI_PASSWORD || secrets.PYPI_TOKEN }}
        repository-url: ${{ inputs.private == 'yes' && 'https://pypi.qtoggle.io' || 'https://pypi.org' }}
