name: Add-on Main

on:
  workflow_call:
    inputs:
      private:
        default: false
        type: boolean
    secrets:
      PYPI_TOKEN:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Replace source version
        uses: qtoggle/actions-common/actions/lint-python@v1
  build:
    name: Build Package
    if: startsWith(github.ref, 'refs/tags/version-')
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Build Python package
        uses: qtoggle/actions-common/actions/build-python-package@v1
  publish:
    name: Publish Package
    if: startsWith(github.ref, 'refs/tags/version-')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch dist folder
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ inputs.private && 'github-actions' || '__token__' }}
          password: ${{ inputs.private && secrets.PRIVATE_PYPI_TOKEN || secrets.PYPI_TOKEN }}
          repository-url: ${{ inputs.private && 'https://pypi.qtoggle.io' || 'https://pypi.org' }}
