name: Add-on Main

on:
  workflow_call:
    inputs:
      private:
        default: false
        type: boolean
    secrets:
      PYPI_TOKEN:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Replace source version
        uses: qtoggle/actions-common/actions/lint-python@wip
  build:
    name: Build Package
    if: startsWith(github.ref, 'refs/tags/version-')
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Build Python package
        uses: qtoggle/actions-common/actions/build-python-package@wip
  publish:
    name: Publish Package
    if: startsWith(github.ref, 'refs/tags/version-')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Publish Python package
        uses: qtoggle/actions-common/actions/publish-python-package@wip
        with:
          private: ${{ inputs.private }}
